name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Update archive
        run: sudo apt-get update -qq
      - name: Install dependencies
        run: sudo apt-get install -qq
          gcc
          gcc-arm-linux-gnueabi libc-dev-armel-cross
          git device-tree-compiler qemu-user
          python3-pip ninja-build
      - name: Install minimum meson
        run: pip3 install --user meson~=0.63
      - uses: actions/checkout@v2
      - name: arm32
        # meson compile requires 0.54, but Ubuntu 20.04 ships 0.53, so run ninja directly
        run: meson setup build-arm --cross-file meson/arm-linux-gnueabi-gcc.ini && ninja -C build-arm
      - name: native
        run: meson setup build-native && ninja -C build-native

